on:
  push:

jobs:
  first:
    steps:
      - uses: http://sigyl.com:3000/actions/checkout@v3.5.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - uses: ./.gitea/actions/tea
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: result
        run: |
          pwd
          ../tea pr ls -o=simple
      - name: Hello world action step
        id: hello
        #uses: ./.gitea/actions/docker
        uses: alpine:3.14
        with:
          who-to-greet: 'Mona the Octocat!!'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
