name: pr-open
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    types:
      - reopened
    branches:
      - 'main'

jobs:
  build-branch:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/RouxAntoine/checkout/tree/v3.5.4
      - uses: http://sigyl.com:3000/actions/checkout@v3.5.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - uses: ./.github/actions/tea
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - uses: http://sigyl.com:3000/actions/setup-node@v3
        with:
          node-version: '20'
      - uses: http://sigyl.com:3000/actions/batch2yaml@master
        with:
          action: xml
          path: '.'
      - name: get PR number
        run: |
          echo ::set-env name=PR::$(.../tea pr ls -f=base,head,index | grep "| main | ${{ github.ref_name }} |" | tr -d ' ' | tr "|" "\n" | head -n 4 | tail -1)
      - name: get build branch name
        run: |
          firstString=${{ github.ref_name }}
          secondString="build"
          echo ::set-env name=BUILD_BRANCH::${firstString/develop\//"$secondString"\/}
      - name: GIT commit and push all changed files
        env: 
          CI_COMMIT_MESSAGE: Reopened PR converted to xml.
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git checkout -b ${{ env.BUILD_BRANCH }}
          git add -A
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }} yml files converted to xml"
          git push origin HEAD:${{ env.BUILD_BRANCH }}

      - name: make pull request comment
        run: |
          ../tea c $PR "this branch has been built on [${{ env.BUILD_BRANCH }}](${{ github.serverUrl }}/${{ github.repository }}/src/branch/${{ env.BUILD_BRANCH }})"
          