name: convert-to-yml
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - 'build/**'
jobs:
  develop-branch:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/RouxAntoine/checkout/tree/v3.5.4 
      - uses: RouxAntoine/checkout@v3.5.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 1
      - uses: ./.github/actions/tea
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: ./.github/actions/git-prep
      - uses: ./.github/actions/branch-name
        id: develop-branch
        with:
          name: ${{ github.ref_name }}
          replace: build
          with: develop 
      - uses: https://sigyl.com:3001/actions/batch2yaml@master
        with:
          action: yml
          path: '.'
      - uses: ./.github/actions/i-have-changes
        id: has-changes
      - name: commit if changed
        if: ${{ steps.has-changes.outputs.changes }} == "true"
        run: |
          git add -A
          git commit -a -m "${{ github.ref_name }} -> ${{ steps.develop-branch.outputs.branch }}"
      - name: push
        run: |
          if [[ $(git branch -r | grep -Fx "  origin/${{ steps.develop-branch.outputs.branch }}" | wc -c) -eq 0 ]]; then
            ls
            git log -5
            git status
            git rebase -Xtheirs origin/main
            ls
            git log -4
            git status
            echo no development branch so pushing
            git push origin HEAD:${{ steps.develop-branch.outputs.branch }};
            if [[ $(../tea pr ls -f=base,head -o=csv | grep grep "\"main\",\"${{ steps.develop-branch.outputs.branch }}\"" | head -c1 | wc -c) -eq 0 ]]; then
              ../tea pr c --base=main --head=${{ steps.develop-branch.outputs.branch }} --description="
            development pull request 
            this PR is instigated by and will been built on [${{ github.ref_name }}](${{ github.serverUrl }}/${{ github.repository }}/src/branch/${{ github.ref_name }})
              " -t="WIP: ${{ github.event.head_commit.message }}"
            fi
            echo 'pushed new branch and created pr';
          else
            if [[ $(git diff origin/${{ steps.develop-branch.outputs.branch }} | wc -c) -ne 0 ]]; then
              #git rebase -Xtheirs origin/${{ steps.develop-branch.outputs.branch }}
              git clone ${{ github.serverUrl }}/${{ github.repository }} ../cloned
              git -C ../cloned fetch origin #--depth=1
              git -C ../cloned checkout ${{ steps.develop-branch.outputs.branch }} || git -C ../cloned checkout -b ${{ steps.develop-branch.outputs.branch }}
              mv ../cloned/.git ..
              rm -rf ../cloned
              cp -r . ../cloned
              rm -rf ../cloned/.git
              mv ../.git ../cloned
              mv .git/config ../cloned/.git
              rm -r ./*
              rm -r .git
              mv ../cloned/* .
              mv ../cloned/.git .
              git add -A
              git commit -a -m "${{ github.ref_name }} -> ${{ steps.develop-branch.outputs.branch }}"
              git push origin HEAD:${{ steps.develop-branch.outputs.branch }};
            else
              echo 'no changes so no push'
            fi;
          fi
