name: build-develop-branch
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  delete-develop:
    # if: ${{ ! startsWith(github.head_ref, 'develop/') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.head_ref }}
      - uses: RouxAntoine//checkout@v3.5.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: delete develop branch
        id: delete_develop_branch
        run: git push origin --delete ${{ github.head_ref }}
        continue-on-error: true
      - uses: mainmatter/continue-on-error-comment@v1
        with:
          repo-token: ${{ secrets.BOT_TOKEN }}
          outcome: ${{ steps.delete_develop_branch.outcome }}
          test-id: Error code ${{ matrix.code }}
      - name: get build branch name
        run: |
          firstString=${{ github.head_ref }}
          secondString="build"
          echo ::set-env name=BUILD_BRANCH::${firstString/develop\//"$secondString"\/}s      
      - name: delete build branch
        run: git push origin --delete ${{ env.BUILD_BRANCH }}
  