name: build-develop-branch
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: json
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
  delete-develop:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.head_ref }}
      - uses: RouxAntoine/checkout@v3.5.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: delete develop branch
        id: delete_develop_branch
        run: git push origin --delete ${{ github.head_ref }}
        continue-on-error: true
      - uses: mainmatter/continue-on-error-comment@v1
        with:
          repo-token: ${{ secrets.BOT_TOKEN }}
          outcome: ${{ steps.delete_develop_branch.outcome }}
          test-id: Error code ${{ matrix.code }}
      - uses: ./.github/actions/branch-name
        id: build-branch
        with:
          name: ${{ github.head_ref}}
          replace: develop
          with: build
      - name: delete build branch
        run: git push origin --delete ${{ steps.build-branch.outputs.branch }}
