name: build-develop-branch
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: json
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
