on:
  push:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: http://sigyl.com:3000/actions/checkout@v3.5.4
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: Hello world action step
        id: hello
        uses: ./.github/actions/docker
        #uses: alpine:3.14
        with:
          who-to-greet: 'Mona the Octocat!!'
          token: ${{ secrets.BOT_TOKEN }}
