on:
  push:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: echo starting!
      - run: pwd
      - run: ls -al
      - uses: gilesbradshaw/checkout@fix/1370-sub-path-missing
      - run: git remote -v
      #  with:
      #    token: ${{ secrets.BOT_TOKEN }}
      #- name: another
      #  uses: ./.github/actions/another
      #- name: tea-3
      #  uses: ./.github/actions/tea
      